### PR TITLE
Ark Testcase (Sprite from a Snes game)

### PR DESCRIPTION
**Pull request by Shudouken**
I don't know if this is relevant or not but I was playing around with your scalers and found that you can clearly see lots of differences in this one.
Also, firefox can't for some reason display these images correctly for me, espcially haasnsoft looks totally different in chrome, no idea what's going on here
https://0x0.st/K5.png

### CODE REVIEW

**Comment by CamilleScholtz** [comment]
The images look just fine for me (I think). Using Firefox 36.0.3.
http://a.pomf.se/wapqgq.png

**Comment by Shudouken** [comment]
Yes, looks fine, probably something wrong with my settings

**Comment by haasn** [comment]
About the color differences, I just realized that imagemagick includes colorimetry information (queried from X or other places) in the tags by default.

I've stripped them from the current images, and fixed the script accordingly. I will re-make your images if you don't mind.

**Comment by haasn** [comment]
Added it in https://github.com/haasn/mpv-upscalers/commit/f6b5e06766434b06353b19408f14f976f92e882f.

**Pull request closed without merging**
